# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build with different min/target SDK"
	  lane :buildWithMinTargetSdk do |options|
		gradle(
		  properties: {
			"minSdk" => "19",
			"targetSdk" => "31"
		  },
		  task: "assemble #{options[:additionalParameters]}"
		)
  end

  desc "Build with other gradle version"
    lane :buildWithOtherGradle do |options|
     set_properties_value(
        path: "./gradle/wrapper/gradle-wrapper.properties",
        key: "distributionUrl",
        value: "https\://services.gradle.org/distributions/gradle-#{options[:gradle]}-bin.zip"
     )
  	gradle(
  	  properties: {
  		"gradle" => options[:gradle]
  	  },
  	  task: "assemble #{options[:additionalParameters]}"
  	)
  end

  desc "Build with other Xcode version"
  	lane :buildWithOtherXcode do |options|
  		xcversion(version: options[:xcode])
  end
end
