# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  	lane :test do
    	gradle(task: "test")
  	end

  desc "Change build.gradle file content"
    lane :changeBuildGradleContent do |options|
      modifyFile("#{__dir__}/../#{options[:file]}", "#{options[:existingKey]}", "#{options[:modifiedValue]}")
  end

  def modifyFile(filePath,existingKey,modifiedValue)
  	text = File.read(filePath)
    new_contents = text.gsub(/#{existingKey}.*/, "#{existingKey} #{modifiedValue}")
    puts new_contents
    File.open(filePath, "w") {|file| file.puts new_contents }
  end
end

platform :ios do
  desc "Change Xcode version"
  	lane :buildWithOtherXcode do |options|
  		xcversion(version: options[:xcode])
  end
end
